# Port
server.port=8080

# Default to h2 profile for local development if not specified
spring.profiles.active=h2

# Spring Data JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (Should be at least 256-bit strong)
app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwtExpirationMs=86400000
